root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "html"]
  include_file = [".env"]
  kill_delay = "5s"

[log]
  time = true

[proxy]
  enabled = true
  app_port = 8080
